### ISSUE TITLE
brightness scenes - cannot switch scene on

### ISSUE THREAD

**Issue by Nerih** [hugobloem/stateful_scenes#1]
Hi,

I have two scenes, with the same light entity.

Scene 1 set the brightness to high
Scene 2 sets the brightness to 9%

if i switch Scene 1 on, then i cannot switch scene 2 on, i was hoping it would switch scene 1 off, and switch scene 2 on.

Even if i switch scene 1 off, i cannot switch scene 2 on. It only works if i manually activate the scene 2 through Scenes>Activate, but then scene 1 stops working :)

Is this possible?

Cheers,
Hiren

**Comment by Nerih** [comment]
solved by  going to the scene, pressing the cog, and changing the scene entity id from scene1_duplciate to scene_2

now do not get any issues in the logger: 

Logger: homeassistant.helpers.service
Source: helpers/service.py:833
First occurred: 01:48:17 (19 occurrences)
Last logged: 01:52:46

Referenced entities scene.study_high are missing or not currently available

**Comment by hugobloem** [comment]
Hi Hiren,

Thank you for your issue. Did your scenes have the same name before? Currently, the integration uses the scene name to activate the scenes which may not work for scenes with the same name... I will look into changing this behaviour. 

Re your second issue, is a scene entity part of your scene?

**Comment by Nerih** [comment]
Hi,

First this project is amazing!! 

The scene has a light bulb group. It's a group of ikea zigbee bulbs, which I grouped together using the configuration.yaml

**Comment by hugobloem** [comment]
Hmm I will need to look into this. Will probably be a week before I have time for this though.

**Comment by hugobloem** [comment]
I think I have identified the problem. Scenes are not discovered or updated after the first setup. I need to dive into the HA docs to see how to get the integration to update after e.g. a restart. 

Let me know if you have any experience doing this.

**Comment by Nerih** [comment]
I suggest you listen to the event bus, and look for a call to the service to update or create a state.

There might be a event specifically for scenes but I am not familiar.
