### ISSUE TITLE
Restore on Deactivate - Attribute is always ON after HA restart

### ISSUE THREAD

**Issue by mario4395** [hugobloem/stateful_scenes#111]
Hello Hugo,

The Restore on Deactivate Attribute for my scenes is always ON after a restart of HA.
I want to switch it OFF for all my scenes, but after the reboot I have to do it again...

![image](https://github.com/user-attachments/assets/60595a2e-8919-4ec9-84f4-73ebe483ba9f)

Is this a bug or a feature? 

regards Mario

**Comment by hugobloem** [comment]
Should be fixed in the next update. #109
