### ISSUE TITLE
Option to ignore unavailable entities

### ISSUE THREAD

**Issue by Cheerpipe** [hugobloem/stateful_scenes#130]
Sometimes, one or more entities in a scene may be unavailable which causes the scene switch to be turned off.

It would be great to have an option to indicate that unavailable entities are not evaluated when checking whether a scene is active or not.

Una regla excepcional para este comportamiento deberia ser que si todas las entidades estan no disponibles la escena esta apagada.

I made some super simple dirty in my local to achieve the desired behavior

![image](https://github.com/user-attachments/assets/851aa555-a222-4528-afb8-e15eea8fb108)

**Comment by hugobloem** [comment]
Thank you!
