### ISSUE TITLE
Check for "effect" light attribute 

### ISSUE THREAD

**Issue by Cheerpipe** [hugobloem/stateful_scenes#17]
Some lighrs has an effect attribute that may be used in a escene. Would be nice to check this attribute to determine if an escen is on or off.

Thanks in advance

**Comment by hugobloem** [comment]
Hi,

Sure, I'll try it out and if everything works as expected I'll add it. I am planning a bigger update that also includes the config flow and an option to define the transition time. 

Cheers,
Hugo
