### ISSUE TITLE
Feature: Entity request: Switch 

### ISSUE THREAD

**Issue by Nerih** [hugobloem/stateful_scenes#2]
Hi Hugo.

Would be good to add switches.
An example - I have 8 ikea bulbs and 1 aqara zigbee light switch. All of the aforementioned are paired to my zigbee controller.

In order to turn the lights on, you need to press the aqara switch. In order to control the brightness you set the bulb brightness.

Naturally do both, it's easier to set the states in a scene, I believe this is a very common approach, for homes without a neutral.

Best,
Hiren

**Comment by hugobloem** [comment]
Hi Hiren,

Thank you for your suggestion. I have fixed this in #4 .
