### ISSUE TITLE
Turn scene on is not possible.

### ISSUE THREAD

**Issue by codenotfound1860** [hugobloem/stateful_scenes#28]
Hi there, great project, that would fix a lot of my problems with scenes and HomeKit.
Unfortunately, I can't turn on a scene with the stateful_scene switch, only to turn it off is possible but the state switches if I'm turning it on via the scene directly.
I get the following error message if I try to turn it on.

<img width="670" alt="Screenshot 2023-11-28 um 02 51 04" src="https://github.com/hugobloem/stateful_scenes/assets/97642446/7b8a2b37-a353-411c-b1db-7129fd45a8d5">

I did the default setup for the integration without any errors.
Is this a bug or what did I wrong?

Thanks in advance.

**Comment by hugobloem** [comment]
Hi, thank you for your interest. Does this happen to all switches or one in particular?

**Comment by codenotfound1860** [comment]
That happens to all stateful_scene switches.

**Comment by hugobloem** [comment]
I think I have identified the issue. It may be related to the naming of your scenes. Stateful Scenes tries to find the scene's entity name by using the name you assigned to it. For example, your scene has the name "Daylight Lounge" then it will try to turn on an entity `scene.daylight_lounge`. However, this seems to fail when there is a mismatch between the `entity_id` and its name. I will have a look at how to resolve this.

**Comment by codenotfound1860** [comment]
That's a good point, changed the friendly name previously. I will test it tonight.

**Comment by codenotfound1860** [comment]
That was the problem, and now it's working.
Maybe you can find a solution for it in the future or add this information to the documentation.
Anyways, thank you very much for your quick support and great work.

**Comment by hugobloem** [comment]
Resolved in #31
