### ISSUE TITLE
Feature request: Turn off behavior 

### ISSUE THREAD

**Issue by Nerih** [hugobloem/stateful_scenes#3]
When turning off a scene, turning off is a relative term. For example if you switch between 2 brightness modes. One thing that would assist here is to store the entity state prior to turning on a  scene. And then restoring the before_on state when turning off.

It would be great to have a per scene setting (or global var in the short term) that could toggle this.

Hope this makes sense.

(Just adding a bunch of items here so you can decide if u want to include them in the roadmap)

Happy to assist, as  things take off.

Hiren

**Comment by hugobloem** [comment]
Great suggestion I also thought about implementing this. I will look into developing this.

For now, you could always have two scenes to switch between.

**Comment by hugobloem** [comment]
Introduced in #23
