### ISSUE TITLE
'Unknown error occurred' when adding integration after HA update

### ISSUE THREAD

**Issue by WhaleLordSlayer** [hugobloem/stateful_scenes#36]
I had this running for a few days, then the integration showed as unable to load.  The only change a that time was updating to the newest version of HA.

I have tried a combination of uninstalling, rebooting, reinstalling, etc.  Each time, I get this error when setting it up again.

<img width="499" alt="290291417-e61ed21e-9228-451a-b397-8fa2b8a4ac53" src="https://github.com/hugobloem/stateful_scenes/assets/80280729/f4631c47-76db-43e4-938c-2e3b7b0e20de">

Checking the error logs,  I see this:

WARNING (MainThread) [custom_components.stateful_scenes.config_flow] string indices must be integers, not 'str'
WARNING (MainThread) [custom_components.stateful_scenes.config_flow] 'NoneType' object is not iterable

**Comment by owpac** [comment]
Hello there!

Same error with this in the logs:
```WARNING (MainThread) [custom_components.stateful_scenes.config_flow] 'id'```

**Comment by blizzrdof77** [comment]
Here's my WARNING output:
```Logger: custom_components.stateful_scenes.config_flow
Source: custom_components/stateful_scenes/config_flow.py:62
Integration: Stateful Scenes ([documentation](https://raw.githubusercontent.com/hugobloem/stateful_scenes/main/README.md), [issues](https://github.com/hugobloem/stateful_scenes/issues))
First occurred: 10:44:22 AM (2 occurrences)
Last logged: 10:45:36 AM

'id'```

**Comment by hugobloem** [comment]
Hi, I have not had this issue with any of the HA versions. Has this been resolved?

**Comment by WhaleLordSlayer** [comment]
It stopped for me.  I had to completely remove my scenes.yaml, remove this integration, restart and add them back in.  It eventually started working somehow :)
