### ISSUE TITLE
3 lights setup

### ISSUE THREAD

**Issue by thomasboegl1** [hugobloem/stateful_scenes#54]
Hi,

Thanks for this awesome work!

I face an issue with a 3 light setup : 
- 2 lights on
- 1 light off

I want to set this special light to off. When doing so, it looks like the plugin faces an issue to keep the state of the scene and therefore turns itself off again.

I am happy to help and will try to look at the code if I have some time.

Have a great day,
Thomas.

**Comment by hugobloem** [comment]
Hi Thomas,

Thank you for pointing this out. Just to confirm your scene is configured with 2 lights on and 1 off? Does this happen with a combination of on and off in general that you know?

Cheers,
Hugo

**Comment by thomasboegl1** [comment]
Hi Hugo,

I'll try to replicate this on a virtual env this evening and send you all informations as soon as possible! 
Issue could be on my side....

Thanks for your time.

- 2 Tuya lights
- 1 Yeelight light

**Comment by thomasboegl1** [comment]
Hi Hugo,

Sorry for the delay, the issue was in my configuration and I was able to handle it :)

Sorry for the inconvenience and thanks for the time!
