### ISSUE TITLE
Add support for thermostats

### ISSUE THREAD

**Issue by MrMuetze** [hugobloem/stateful_scenes#69]
Hi,
I just recently stumbled upon this repo and love the concept! For my use cases I would need support for thermostats/smart radiator valves, so basically the "climate" category of entities if I understand this right. I just recently dove into HA so I'm not familiar with all the details, so please let me know if I can provide additional information. :)

I think the relevant values to observe would be the "on/off" state of a thermostat and, if "on" the target temperature.

Best regards!
Björn

**Comment by hugobloem** [comment]
Thank you for your recommendation. I have added thermostats now.

**Comment by MrMuetze** [comment]
Oh wow I have to thank you for that quick response! :) Already experimented with this integration a bit and it seems to be exactly what I've been looking for!
