### ISSUE TITLE
Switch turn off after 4seconds

### ISSUE THREAD

**Issue by WeisserWolf611** [hugobloem/stateful_scenes#74]
I cant get it working. If I use the switch (switch.abend_stateful_scene) the switch turned off automatically after 4-5seconds.
I use version 1.2.1. I can't find any solution. Could you please help?

![4c8c7bd55f0a03d073c96dc158ca06225f6cfb6d](https://github.com/hugobloem/stateful_scenes/assets/100164207/d304e6a3-6e24-43c2-8782-53295bb7ab86)

**Comment by hugobloem** [comment]
What devices do you have inside the scene? Have you looked at whether they change their state after the scene has been turned on?
