### ISSUE TITLE
v1.0.3beta1 multiple integration entries

### ISSUE THREAD

**Issue by pgale** [hugobloem/stateful_scenes#82]
Not sure if this is a bug or by design:

When adding entries (running through the config), multiple 'stateful scenes' are added. I would think that they should all be grouped together? I don't think you can edit the config either?
![Screenshot 2024-04-27 162242](https://github.com/hugobloem/stateful_scenes/assets/513044/3e4b198b-0e9c-46f5-8239-e3dcd95acd9e)

**Comment by hugobloem** [comment]
I guess it's more a limitation of the functionality at the moment. I will need to add a reconfigure option such that it is possible to add new scenes. Somewhat related to this I think a button to relearn the scene would be good as well.
