### ISSUE TITLE
Add color_temp attribute

### ISSUE THREAD

**Issue by Cheerpipe** [hugobloem/stateful_scenes#86]
Hi, me again asking for adding new attributes.

Some bulbs have different channels for RGB modes and Color Tempo modes so, may be possible to add color_temp as attribute for scenes where i need bulbs y Color Tempo mode instead of RGB? I think some users may also use rgbw_color and/or rgbww_color.

Thaks in advance

**Comment by hugobloem** [comment]
For any light that supports at least colour temperatures the RGB colour is calculated by Home Assistant. If you design scenes via the built-in scene editor these are stored automatically.
