### ISSUE TITLE
Restore on default switch state is not saved-restored across HA restarts

### ISSUE THREAD

**Issue by Cheerpipe** [hugobloem/stateful_scenes#99]
Hi.

First of all, thanks again for this amazin integration. Can't live without it.

Well, since last beta the state of Restore On Deactivate switch is always on after HA restart. I am not a python nor HA developer by i take some time to check the code and learned some things.

If i am correct, `RestoreOnDeactivate `class should  inheriting `SwitchEntity` and `RestoreEntity` but currently only inherit `SwitchEntity` so the state is not being saved/restored in HA Storage.

I did some changes to the switch entity and now restore on deactivate switch state survives HA restarts.

This is the modified code:

https://github.com/Cheerpipe/stateful_scenes/commit/90beaa341c1bdbcafa80dde3d3c645c05580da98 (Pls ignore change at line 179).\

One remaining bug is switch state is always stored as true after integration is configured, maybe because of #95.

**Comment by hugobloem** [comment]
Thank you for providing the code 🙏, I have implemented and merged it now.
